apiVersion: v1
kind: Service
metadata:
  name: jenkins-ext-ip
spec:
  selector:
    my_pod: my_jenkins
  ports:
    - name: http
      protocol: TCP
      port: 8085
      targetPort: 8080
  externalIPs:
    - 172.31.43.250
