apiVersion: v1
kind: Service
metadata:
  name: jenkins-nodeport
spec:
  type: NodePort
  selector:
    my_pod: my_jenkins
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8080
      nodePort: 30008

